task :default => 'morning:daily_routine'

namespace :morning do
  desc "Stop the alarm"
  task :turn_off_alarm do
    puts "Turned off alarm"
  end

  desc "Make myself good looking"
  task :groom_self do
    puts "Brushed teeth"
    puts "Shaved"
    puts "Waxed beard"
  end

  desc "gotta drink"
  task :make_coffee do
    puts "Made #{ENV['COFFEE_CUPS'] || 2} cups of coffee"
  end

  desc "hanging with the dog"
  task :walk_dog do
    puts "Walked the dog"
  end

  desc "Pull yourself together for the day"
  task :daily_routine => [:turn_off_alarm, :groom_self, :make_coffee, :walk_dog] do
    puts "Ready for another day"
  end

end


namespace :morning do
  task :groom_self do
    puts "Scrape off scabs"
  end
end

namespace :afternoon do
  desc "Make special afternoon coffee"
  task :make_coffee do
    Rake::Task['moring:make_coffee'].invoke
    puts "Add rum"
  end
end
