# Publisher
puts "\nSetting Up Publishers\n"
Publisher.create(name: "DC Comics")
Publisher.create(name: "Marvel Comics")

Publisher.all.each{ |p| puts "Created: #{p.name}" }

# Heroes
# DC COMICS
puts "\nSetting Up Heroes\n"
Hero.create(name: "Superman", description: "Whether you label Superman as the first superhero depends on what your definition of \"superhero\" is. But whether or not he was first, he's undoubtedly the best. Superman is the purest distillation of everything we love about heroes. He has the tragic, almost Biblical origin - a baby is sent hurtling from a doomed planet, is adopted by a human couple, and grows up to become the world's premiere defender of Truth, Justice, and the American Way. Thanks to his Kryptonian physiology, he's a hero of almost unlimited strength.<br /><br />But what makes Superman great is that it's not about \"the American Way.\" He cares about everyone, regardless of creed, color, or nationality. He's a man who should be profoundly lonely and unhappy in the universe, but instead embraces his new home and shows us all a heroic ideal to aspire to. He's become an international icon arguably more famous than Mickey Mouse, and he endures every revamp, reboot, and re-imagining largely unchanged. What worked 70 years ago still works today.", powers: "Seemingly all of them", rating: 3, publisher_id: 1)
Hero.create(name: 'The Atom', description: "He shares his superhero name with the Golden Age Atom, but Ray Palmer is more a scientist than a pugilist. His patented size-changing belt allows him to shrink down to subatomic size. This versatile power allows for all manner of superhero adventures, from mind-bending sci-fi to swashbuckling adventure. Ray's fortunes have risen and fallen in recent years, from the tragic fallout of Identity Crisis to his return to his return to prominence to his current, reduced role within the New 52. But regardless, he remains the greatest hero to call himself \"The Atom.\"", powers: 'Alter size, fly', rating: 6, publisher_id: 1)
Hero.create(name: "John Constantine", description: "John Constantine would probably resent being included on this list. This crafty magician tends to look out for himself alone, and his friends usually end up paying the consequences. But even though his morals are often questionable, and his smoking habit excessive, Constantine has saved the world plenty of times. He debuted in the pages of Swamp Thing, spun out into his own long-running solo series, ensured a subpar movie adaptation, and has recently been reintegrated into the DCU with the New 52. Constantine now leads a Justice league squad of his own, but he'd prefer if you didn't use that name.", powers: "Deception, Occultism, Prestidigitation", rating: 8, publisher_id: 1)
Hero.create(name: "Martian Manhunter", description: "As tragic as Superman's origin is, at least he was just a baby when he was sent rocketing away from his doomed world. J'onn J'onzz had to watch his family, his people, and his entire Martian culture burn down before his eyes. But rather than wallowing in misery to the end of his days, the Martian Manhunter made a second home on Earth. He's found plenty in human culture worth fighting for, including his favorite delicacy - Choco cookies. And with his Superman-level abilities, he's a force to be reckoned with. J'onn has been a recurring member of the Justice League in the comics and animated series, and we imagine it's only a matter of time before he appears on the big screen as well.", powers: "Flight, Super Strength", rating: 5, publisher_id: 1)
Hero.create(name:"The Flash (Barry Allen)", description: "Barry Allen's debut in 1956 is credited with kicking off the Silver Age of comics. Barry assumed the mantle of the Flash from Golden Age hero Jay Garrick. He quickly proved to be one of the most popular of DC's new wave of heroes thanks to his almost limitless speed powers, his colorful adventures across time and space, and his neverending struggle to balance his superhero antics with his professional and personal lives. Despite his incredible speed, Barry always has a reputation for being late. Barry was killed off in the 1986 story Crisis on Infinite Earths, casting a long shadow on the rest of the DCU in the process. But he's since returned and taken up the mantle of the Flash all over again.", powers: "Speedforce. It's just hax", rating: 8, publisher_id: 1)

# MARVEL COMICS
Hero.create(name: "Spiderman", description: "Bitten by a radioactive spider, high school student Peter Parker gained the speed, strength and powers of a spider. Adopting the name Spider-Man, Peter hoped to start a career using his new abilities. Taught that with great power comes great responsibility, Spidey has vowed to use his powers to help people.", powers: "Super Strength, Spider Sense, Clings to most walls", rating: 7, publisher_id: 2)
Hero.create(name: "Hulk", description: "Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets.", powers: "Super Strength, Is Green", rating: 5, publisher_id: 2)
Hero.create(name: "Thor", description: "As the Norse God of thunder and lightning, Thor wields one of the greatest weapons ever made, the enchanted hammer Mjolnir. While others have described Thor as an over-muscled, oafish imbecile, he's quite smart and compassionate. He's self-assured, and he would never, ever stop fighting for a worthwhile cause.", powers: "Super Strength, God of Thunder", rating: 9, publisher_id: 2)
Hero.create(name: "Iron Man", description: "Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.", powers: "Suit, Intelligence", rating: 7, publisher_id: 2)
Hero.create(name: "Luke Cage", description: "Marvel's Luke Cage, or simply Luke Cage, is an American web television series created for Netflix by Cheo Hodari Coker, based on the Marvel Comics character of the same name. ... Mike Colter stars as Luke Cage, a former convict with superhuman strength and unbreakable skin who now fights crime.", powers: "Nearly indestructible skin, Super strength", rating: 6, publisher_id: 2)

Hero.all.each{ |p| puts "Created: #{p.name}" }
# Villains
# DC COMICS
puts "\nSetting Up Villains\n"
Villain.create(name: "The Joker", description: "The Joker, Clown Prince of Crime, is Batman's arch-nemesis. An agent of chaos known for his malicious plots, wacky gadgets and insidious smile, he has caused Batman more suffering than any other villain he has ever faced. His origin, name, and true motivations remain a mystery.", powers: "Insanity", rating: 7, publisher_id: 1)
Villain.create(name: "Lex Luthor", description: "Lex Luthor, Superman's arch-nemesis, is one of the most gifted beings alive, whose hatred of \"interfering aliens\" pushes him down the path of a sociopath. Known for his \"ends justifies the means\" approach to life, his single-minded and often brutal focus puts him at odds with The Man of Steel. Lex Luthor is arguably DC Comics' most iconic villain. Played in film by Gene Hackman, Kevin Spacey and Jesse Eisenberg.", powers: "High Intelligence", rating: 8, publisher_id: 1)
Villain.create(name: "Darkseid", description: "Worshipped as the \"God of Evil\", Darkseid is one of the most powerful beings in existence and the supreme monarch of planet Apokolips. Considered as one of the Justice League's worst adversaries, the greatest enemy of New Genesis and one of the greatest threats to the DC Multiverse, he seeks to bend everything and everyone to his will and remake the cosmos in his image, while searching for the Anti-Life Equation.", powers: "Super Strength, Many other things", rating: 7, publisher_id: 1)
Villain.create(name: "Vandal Savage", description: "Vandal Savage, the immortal tyrant, has been witness to humanity's growth from the dawn of civilization, and his desire to control mankind has led him into conflict with many heroes of the DC Universe.", powers: "Things and stuff", rating: 4, publisher_id: 1)

# MARVEL COMICS
Villain.create(name: "M.O.D.O.K", description: "M.O.D.O.K.’s mission statement is clear. It’s right there in his name - Mental Organism Designed Only for Killing. This oversized villain was bioengineered by the scientists of A.I.M. to be the ultimate super-smart, tyrannical leader. And while his appearance may be comical, M.O.D.O.K. is certainly good at killing things.
<br /><br />
               M.O.D.O.K. is a multi-purpose villain in the Marvel Universe. He’s an enemy to many heroes, especially the Avengers and Fantastic Four. His master plans can be fiendishly brilliant or laughably silly, and sometimes both at once. There are even multiple versions of MODOK floating around the Marvel multiverse, including M.O.D.A.M. (Mental Organism Designed for Aggressive Maneuvers) and M.O.D.O.G. (Mental Organism Designed Only for Genocide).", powers: "Being a trashcan", rating: 6, publisher_id:2)
Villain.create(name: "Annihilus", description: "The Marvel Universe has a companion universe in the form of the anti-matter-based Negative Zone. And in the Negative Zone, Annihilus reigns supreme. This armored, insect-like villain wields the Cosmic Control Rod, a weapon granting him control of the Negative Zone’s billions of inhabitants.
<br /><br />
               Annihilus began his career as a foe of the Fantastic Four. But no story showcased the threat he poses to all life like the Annihilation storyline, where he led an invasion force that nearly succeeded in subjugating the entire universe. The galaxy’s greatest heroes have been forced to accept that there’s no stopping Annihilus, only living with the constant threat of total annihilation.", powers: "Anti-matter stuff", rating: 5, publisher_id: 2)
Villain.create(name: "Kingpin", description: "What if there was a secret mastermind controlling all the criminal activity in New York City, from the street corner to the boardroom? That might be impossible in real life, but in the Marvel Universe, that’s where the Kingpin comes in.
<br /><br />
               Wilson Fisk rose from obscurity to become one of the most powerful crime lords in the world. His money and resources make him untouchable to politicians and law enforcement, while his army of hired thugs and assassins makes it all but impossible to topple his regime. When even heroes like Spider-Man and Daredevil have failed to defeat Fisk, you know he’s a force to be reckoned with.", powers: "Above average strength", rating: 8, publisher_id: 2)
Villain.create(name: "Apocalypse", description: "Apocalypse is one of the world’s first mutants, born in the days of Ancient Egypt and forced to learn at an early age that only the strong survive. Apocalypse used Celestial technology to make himself the strongest person alive. For millennia he traveled the world, battling men like Thor and Dracula, inspiring a cult of followers and furthering the process of evolution. Now in the present day, Apocalypse is determined to make sure only the strong survive, whether they be human or mutant.
<br /><br />
               Apocalypse sees himself as the rightful master of the world, and with a vast array of powers including shapeshifting, psionic abilities, and body-swapping, he certainly has the means to make it happen.", powers: "Taken from celestials", rating: 10, publisher_id: 2)
Villain.create(name: "Thanos", description: "The name “Thanos” is enough to inspire dread in almost every living being in the universe. Thanos is a tyrant obsessed with Death. Not just the concept of death or the act of killing, but the literal personification of Death herself. Thanos would happily kill entire worlds to win her favor -- they call him the Mad Titan for a reason.
<br /><br />
               And perhaps no Marvel villain has racked up quite a body count. Thanos has a habit of amplifying his already considerable strength with cosmic artifacts like the Cosmic Cube or the Infinity Gauntlet. The latter weapon briefly morphed him into an omnipotent being, allowing him to murder half the living beings in the universe as tribute to Death. He only lost ultimate power because of a latent self-loathing streak. That quality, as much as his awesome power or his boundless ambition, is what makes Thanos a fascinating figure.", powers: "Most of them", rating: 10, publisher_id: 2)
Villain.all.each{ |p| puts "Created: #{p.name}" }
